# Generated by Django 4.0.3 on 2022-03-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('nama', models.CharField(max_length=40)),
                ('alamat', models.CharField(max_length=50)),
                ('Pass', models.CharField(max_length=30)),
            ],
        ),
    ]
