# Generated by Django 4.0.3 on 2022-03-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_restt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personal',
            table='personal',
        ),
    ]
